### ISSUE TITLE
Subtitles are getting cutoff at the bottom all of the sudden

### ISSUE THREAD

**Issue by casolorz** [googlecast/CastReferencePlayer#13]
Last night I noticed hbo subtitles were cutoff at the bottom and today I've started getting complaints as well for my own app that is based on this reference player. I did reproduce the issue myself but haven't had time to troubleshoot it yet.

**Comment by entertailion** [comment]
Here is a temporary workaround until we release an update with the real fix. Add this to your CSS:
video::-webkit-media-text-track-container {
position: fixed;
top: 0;
left: 0;
right: 0;
bottom: 0;
max-height: 685px;
}

This might have issues for international languages.﻿

**Comment by entertailion** [comment]
This issue has been fixed a while ago. Check again.
