### ISSUE TITLE
Videos are getting stretched

### ISSUE THREAD

**Issue by casolorz** [googlecast/CastReferencePlayer#14]
I think after the scrollbars fix was applied videos that are of a smaller aspect ratio are all of the sudden getting stretched. I tested against the app id CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID and the videos don't get stretched there. 

I am still testing to make sure it was the scrollbars fix that did it.

**Comment by mntgoat** [comment]
I have just confirmed, the fix on #12 is stretching videos.

**Comment by alexrmacleod** [comment]
@casolorz 

I found playing around with the css helped improve the video aspect ratio

`.player img, .player video {
  display: none;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: #000;
  background-size: contain; /*cover*/
  background-position: center;
  background-repeat: no-repeat;
  object-fit: contain; /*fill     conver works better but not perfect*/ 
}`
