### ISSUE TITLE
headless chromecast, loadMedia never completes

### ISSUE THREAD

**Issue by kzahel** [googlecast/CastReferencePlayer#15]
I develop my Chromecast app where I don't have an external monitor. I noticed that a loadMedia request never completed, even though the player was indeed streaming the content.

I changed a line in sampleplayer.transition_ to always immediately something() just like in the audio case, because the transition_ is looking for a webkitTransitionEnd which never fires when there is no display. Interesting! Anyway I am not sure how you can detect "headless" operation in the player.js and allow it to complete anyway, nor whether you would want to do this anyway, but I am sharing the information here.

**Comment by ghenry22** [comment]
Haha I'm not the only one!  I tested with my chromecast audio at home and all was working great, I bought a regular (non-audio) chromecast to test with as well but I didn't have a HDMI input on my second monitor at work so just left it unplugged and assumed that would be an issue but I see exactly this behaviour.  No error but no success callback ever fires for loadmedia which means you don't receive a media object in the sender to control the playback.

It is a bit of an obscure use case as you can't actually play anything without a connection so maybe in this case onError should be called with a "output connection not available" or similar meaningful message.

Just wasted a few hours putting in break points and trying to figure this out when I hit this suspicion and upon searching found this issue.

**Comment by entertailion** [comment]
You can determine the device capabilities: https://developers.google.com/cast/docs/audio
