### ISSUE TITLE
URL to stream not as contentId

### ISSUE THREAD

**Issue by enjikaka** [googlecast/CastReferencePlayer#16]
For one application I'm making I need to generate the URLs for the media on the receiver with auth tokens.

The senders send the receiver an id in contentId, which I on the receiver through some ajax callbacks convert into a URL for a stream. To play this, I need to replace contentId with the generated URL. But this breaks "play previous" requests from the senders. Probably because they assume contentId is still and ID, and not an URL?

How would I solve this?

**Comment by entertailion** [comment]
If the sender is telling the receiver to play the previous track, you should be able to apply the same logic for converting the contentId to a URL. This is beyond the scope of the player and entirely up to your custom logic.

**Comment by enjikaka** [comment]
I solved this by setting the generated source URL directly on the this.mediaElement_. When I created an issue I was too into trying to change it in loadDefault_ via cast.receiver.MediaManager.Event somehow.
