### ISSUE TITLE
Receiver debug tools can't be reached

### ISSUE THREAD

**Issue by enjikaka** [googlecast/CastReferencePlayer#17]
...due to Object.observe being gone in Chrome 50.

This URL is not updated on the receiver debug page on `<IP>:9222`, so please keep this issue open until Google has resolved this problem by updating the URL in the receiver or hotfix'd Chrome to add back Object.observe again. **This should be resolved as soon as possible since the workaround is cumbersome for all developers working with receiver apps.**

Temporary workaround:
Change `https://chrome-devtools-frontend.appspot.com/` to `chrome-devtools://devtools/remote/` and add `?remoteFrontend=true` to the end of the URL and you will be able to reach the debugging tools again.

**Comment by mntgoat** [comment]
From my testing it appears to be fixed on the latest chromecast firmware.

**Comment by entertailion** [comment]
Moving forward, we recommend using chrome://inspect/#devices

**Comment by enjikaka** [comment]
Thanks Leon.
