### ISSUE TITLE
Update Cast documentation for debugging

### ISSUE THREAD

**Issue by enjikaka** [googlecast/CastReferencePlayer#18]
The documentation for debugging cast ( https://developers.google.com/cast/docs/debugging#chrome ) does not contain information that chrome://inspect/#devices is to be used for debugging the receiver from now on.

**Comment by alexrmacleod** [comment]
If you wish to watch whats going on, using a Chrome browser, connect to <IP of your Chromecast>:9222 and debug your receiver. A good place to start is looking at the console log.

This doesn't seem to work? am I missing something?

**Comment by entertailion** [comment]
Using port 9222 is no longer supported. Step 3 of that link covers the use of chrome://inspect
