### ISSUE TITLE
Where do you specify CORS requirements?

### ISSUE THREAD

**Issue by dmfrey** [googlecast/CastReferencePlayer#19]
It is my understanding that the receiver needs to specify the CORS and other required headers. I am attempting to use this player as a reference. Where in this code would you specify the CORS and other required headers?

**Comment by dmfrey** [comment]
In the following method, I am adding it as so:

    sampleplayer.CastPlayer.prototype.loadVideo_ = function(info) {

When you define the Host:

      var host = new cast.player.api.Host({
        'url': url,
        'mediaElement': this.mediaElement_
      });
      host.updateSegmentRequestInfo = function (requestInfo) {
        requestInfo.withCredentials = true;
        requestInfo.headers = {};
        requestInfo.headers['origin'] = info.message.media.customData.origin;
        requestInfo.headers['content-type'] = info.message.media.contentType;
        requestInfo.headers['accept-encoding'] = 'gzip';
      }

**Comment by entertailion** [comment]
The Origin header is added by the browser, and cannot be controlled by the developer. You can specify any other header values needed for each request.

**Comment by dmfrey** [comment]
In order to talk to the local backend, that header needs to be present. I
don't control the backend code. Is there another way to provide this info?
I will check with the backend team to see what they can do as well.

**Comment by dmfrey** [comment]
I think what needs to happen is we host the custom receiver on mythtv.org. Then the CORS rules on the local server need to be updated to allow a CORS header from mythtv.org. Then I think it will be ok.  Can you confirm this?

**Comment by entertailion** [comment]
Not sure what you mean by local server. The server that is hosting the content provides the CORS headers as part of each request. The browser will then comply with the CORS server restrictions.

**Comment by dmfrey** [comment]
Sorry, the content that will be presented would be coming from a local MythTV Backend server, typically running in a user's house. I can't expect every user to create a dev console application pointing to a receiver in their house. However, if we can set up the CORS policy to accept requests from the project site, mythtv.org, then the application and receiver only need to be setup once, and the android app can send the request to a cast device to use the receiver to call that content from a local server.  I have verified this works without the CORS headers for plain mp4 files. I just don't have access to the streaming content (which is required for a tv show which would have been recorded in mpeg2, not a supported format for chromecast, so it is transcoded to HLS).

**Comment by Acidburn0zzz** [comment]
thanks ;-)
