### ISSUE TITLE
How to implement own cast.player.api.Player

### ISSUE THREAD

**Issue by CAMOBAP795** [googlecast/CastReferencePlayer#20]
Is there any documentation how to implement own cast.player.api.Player

More details about problem here http://stackoverflow.com/questions/37813492/how-to-implement-own-cast-player-api-player

**Comment by entertailion** [comment]
There are no additional docs on the Player interface other than the API docs.

**Comment by CAMOBAP795** [comment]
@entertailion so for now there is no way to implement custom streaming protocol, my understanding right?

**Comment by entertailion** [comment]
You can write your own player to handle any streaming container format as long as it results in media formats that can be played by the device: https://developers.google.com/cast/docs/media

**Comment by CAMOBAP795** [comment]
@entertailion 

But still is there any 'reference implementation' of custom protocol?

Because documentation is very poor in this aspect, for example I still cannot find the answer on questions:

1. Which JS interfaces should I implement on the way to create own player
2. What is the relationships between `cast.receiver.media.Player` and `cast.player.api.Player`
3. In my particular case I receive PCM audio, which unsupported by according to https://developers.google.com/cast/docs/media but can be played by WebAudio, which works on Chromecast, So I have implemented own `cast.receiver.media.Player`, is this right decision?
4. After my `cast.receiver.media.Player.load` called, I trying to play by sending Play request form Android device, but `cast.receiver.media.Player.play` not called and I'm constantly getting `java.lang.IllegalStateException: No current media session`, looks like my implementation of `cast.receiver.media.Player` wrong but how to troubleshoot it?

**Comment by entertailion** [comment]
You need to implement the 
cast.receiver.media.Player interface for you own player and then pass that to the MediaManager constructor:
https://developers.google.com/cast/docs/reference/receiver/cast.receiver.MediaManager

The rest of the receiver logic for managing media should be the same as with the default media element.

**Comment by CAMOBAP795** [comment]
ok thanks,

About `java.lang.IllegalStateException: No current media session` 

Does custom `cast.receiver.media.Player` have any influence of media session?

When I replace custom `cast.receiver.media.Player` with `HTMLMediaElement` in `cast.receiver.MediaManager` the problem above disappear

But how can I troubleshoot this?
1. Default `cast.receiver.media.Player` implementation obfuscated
2. There is no reference implementation of `cast.receiver.media.Player`
3. There is not enough documentation about how to implement `cast.receiver.media.Player` except interface description

**Comment by entertailion** [comment]
Yes, cast.receiver.media.Player affects the media session. You should log the calls to the interface methods. It is also possible to extend the MediaManager by overwriting its own methods and then calling the original method implementations.

**Comment by CAMOBAP795** [comment]
I found more information [here](https://developers.google.com/cast/docs/reference/messages#MediaStatus)

> Unique ID for the playback of this specific session. This ID is set by the receiver at LOAD and can be used to identify a specific instance of a playback. For example, two playbacks of "Wish you were here" within the same session would each have a unique mediaSessionId.

I tried to set [RequestData.mediaSessionId](https://developers.google.com/cast/docs/reference/receiver/cast.receiver.MediaManager.RequestData#mediaSessionId) in in [MediaManager.onLoad](https://developers.google.com/cast/docs/reference/receiver/cast.receiver.MediaManager#onLoad)

Still no success.

@entertailion Does `MediaManager.onLoad` right place to set `mediaSessionId` ?

**Comment by entertailion** [comment]
I believe the id is assigned by the Receiver SDK. You should only have to provide the media metadata.

**Comment by CAMOBAP795** [comment]
@entertailion so If Receiver SDK didn't assigned it, May I thing that this is a bug in Receiver SDK?

**Comment by entertailion** [comment]
It is more likely that you are doing something wrong. Are there any error messages in the receiver log?

**Comment by CAMOBAP795** [comment]
No error message in receiver log.

I reported separate bug with logs and minimal reproducible sample https://github.com/googlecast/CastReferencePlayer/issues/26
