### ISSUE TITLE
load & preload

### ISSUE THREAD

**Issue by pivanet** [googlecast/CastReferencePlayer#22]
hi,
Could you add some details on load/preload idea you've used in the sample?
There is no such info in the official docs and it's a little bit difficult to get the idea or the problem it is solving.

thank you.

**Comment by entertailion** [comment]
It involves using two players. One for playing the current media and the other for preloading the next media. Once the first player media ends, the next player can start playing without any buffering.

**Comment by pivanet** [comment]
hm... now it's much clear. thanks a lot for details.
