### ISSUE TITLE
Closed captions for HLS streams 

### ISSUE THREAD

**Issue by dacianroman23** [googlecast/CastReferencePlayer#24]
Embedded closed captions -Web Vtt for HLS streams don't work correctly on the receiver. I tried the v3 cast sender sample  for android with the cast reference player sample, and after I enable the English captions in the track chooser dialog, the captions are displayed  only sometimes . If I open the same HLS url in a player, like Quicktime, the embedded captions are working fine. Another issue regarding the captions, is after selecting a track (in my case - the English track) and then if I reopen the track chooser dialog - the none radio button is selected, but this might be connected to the first issue I have mentioned. It might be a parsing problem, but I'm not sure.   The only thing changed on sender was setting my m3u8 url with embeded captions and removing mediatracks.

`MediaInfo.Builder(m3u8 _url )
    .setStreamType(MediaInfo.STREAM_TYPE_BUFFERED)
    .setContentType(mimeType)
    .setMetadata(movieMetadata)
   .setStreamDuration(duration * 1000)
    .setCustomData(jsonObj)
    .build();`

**Comment by entertailion** [comment]
Yes, this is very likely a parsing issue. Please provide a sample stream with tracks and a complete log and file an issue: https://code.google.com/p/google-cast-sdk/issues/list

**Comment by dacianroman23** [comment]
I have added the ticket :  https://code.google.com/p/google-cast-sdk/issues/detail?id=946
Thanks for your help .
