### ISSUE TITLE
What's the recommended way of adding image casting to the CastReferencePlayer?

### ISSUE THREAD

**Issue by casolorz** [googlecast/CastReferencePlayer#27]
I'm wanting to add simple image casting and my receiver is based on the CastReferencePlayer. I could implement it all with custom messages but I'm thinking it might be doable by creating a separate sampleplayer.Type for images. Is there maybe a sample somewhere?

Thanks.

**Comment by entertailion** [comment]
We don't have a sample for that. The CastReferencePlayer is mainly focused on audio and video playback but could be modified to support images. However, if you only want to do images then it would be much easier to just modify one of the CastHelloText samples and use custom messages.
