### ISSUE TITLE
Widevine HLS playback failed.

### ISSUE THREAD

**Issue by sivarajendranaidu** [googlecast/CastReferencePlayer#29]
Widevine HLS Playback failed.

Trying to play HLS Widevine encrypted asset in chrome-cast with "CastReferencePlayer", content is generated using shaka packager, command is as follows 

" ./packager 'input=/home/siva/Desktop/streams/fifo1.mp4,stream=video,segment_template=/var/www/html/mpeg/hls/cbcs/output$Number$.ts,playlist_name=video_playlist.m3u8' 'input=/home/siva/Desktop/streams/fifo1.mp4,stream=audio,segment_template=/var/www/html/mpeg/hls/cbcs/output_audio$Number$.ts,playlist_name=audio_playlist.m3u8,hls_group_id=audio,hls_name=ENGLISH' --single_segment=false --enable_widevine_encryption=true --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" ". 

But it is not playing.

We have followed this link for reference : https://developers.google.com/cast/docs/mpl_streaming_protocols

![network1](https://cloud.githubusercontent.com/assets/25329744/22830931/5ef5de4e-efce-11e6-9b3f-53be29c6738a.png)
![consolelog](https://cloud.githubusercontent.com/assets/25329744/22830932/5efd050c-efce-11e6-8762-bf3002776b78.png)

Please find the attachments for more information (Screenshots of chromecast logs).

Ref Master File :+1: 

#EXTM3U
#EXT-X-VERSION:5
## Generated with https://github.com/google/shaka-packager version 47363dd-debug
#EXT-X-TARGETDURATION:11
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:11.000,
http://192.168.8.43/mpeg/hls/output1.ts
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,eyJjb250ZW50X2lkIjoiTURFeU16UTFOamM9Iiwia2V5X2lkcyI6WyIxOTE4MTY1RjMxNjg1QUNFQjQxMTFFRkFEQTc2NTI3MSIsIjQxODlDQjE1MjFGQjVDNjI5MUE3OTE5M0Q3M0JGOTVDIiwiNzRFQTFCODAxOTFGNTQ0MkJDNDVGNkFENDU3MkFDMjkiXSwicHJvdmlkZXIiOiJ3aWRldmluZV90ZXN0In0=",IV=0xEC7E06DDAC97059FFBF128BAB5C2DEAA,KEYFORMAT="com.widevine"
#EXTINF:11.000,
http://192.168.8.43/mpeg/hls/output2.ts
#EXTINF:11.000,
http://192.168.8.43/mpeg/hls/output3.ts
#EXTINF:11.000,
http://192.168.8.43/mpeg/hls/output4.ts

**Comment by entertailion** [comment]
We will need to have access to your streams to be able to reproduce the issue. Please fill in this form and provide the stream URL: https://support.google.com/cast-developer/contact/google_cast_contact_us?visit_id=1-636223424964123891-2925031566&hl=en&rd=1
