### ISSUE TITLE
Source Buffer Error on selecting Audio Tracks

### ISSUE THREAD

**Issue by sam2007** [googlecast/CastReferencePlayer#30]
Hi Guys,

We are currently having an issue when trying to play a DASH stream that contains multiple alternative audio.  It seems like the LIbrary takes care of parsing and scanning the available tracks but when a selection was made to select an audio track. We receive this error:

[ 78.478s] [cast.player.api.Host] error: cast.player.api.ErrorCode.PLAYBACK/110 (Failed to execute 'addSourceBuffer' on 'MediaSource': This MediaSource has reached the limit of SourceBuffer objects it can handle. No additional SourceBuffer objects may be added.)

Can you guys point us to the right direction on how to investogate this issue?

Regards,

Ferdinand

**Comment by entertailion** [comment]
Please file a bug and provide a sample stream: https://code.google.com/p/google-cast-sdk/issues/list
