### ISSUE TITLE
Who becomes responsible for messaging in urn:x-cast:com.google.cast.media namespace?

### ISSUE THREAD

**Issue by alex-schwartzman** [googlecast/CastReferencePlayer#31]
Hello.

I have a question for the code. Accordingly to this documentation: https://developers.google.com/cast/docs/reference/messages a custom receiver MUST support exchanging messages namespace urn:x-cast:com.google.cast.media.

While reading the code you have published, I did not spot which part of it is responsible for fulfilling that requirement. Does that mean, that default media player does all the magic, or it means that the receiver is not compliant with Google Cast SDK Additional Developer Terms of Service?

Whatever is the case, I would greatly appreciate, and I beg you to publish some real-real custom receiver, which does not rely on functionality of default mediaplayer, but instead uses some HTML video player like https://github.com/google/shaka-player , or similar. It's very interesting for me, which lifecycle callbacks should be invoked in the Cast SDK framework on the receiver side, so that all necessary playback control messages would be emitted and passed to the sender.

**Comment by entertailion** [comment]
The Cast SDK is responsible for the urn:x-cast:com.google.cast.media namespace.

**Comment by alex-schwartzman** [comment]
Sorry for bothering you again, but it's still not clear for me, how to run shaka-player on the receiver and still comply with the API.

Should I write the wrapper for the player, which recognizes all the Cast API messages and changes shaka-player's state appropriately, or instead there is something in Cast API which will do that for me, and will call my code whenever it is necessary to change the player's state?

As far as I understood, the following string does the magic:
```
this.player_ = new cast.player.api.Player(host);
```
Then it is the responsibility of  cast.player.api.Player to send/receive all the Media Playback Messages, right?

**Comment by entertailion** [comment]
Yes, you would need to support the Player interface and handle all the media namespace messages.
