### ISSUE TITLE
Styled media receiver adding back slash "\" to end or urls. 

### ISSUE THREAD

**Issue by alexrmacleod** [googlecast/CastReferencePlayer#33]
When I run the castVidoes iOS app using their ready to go receiver that is linked to app ID "4F8B3483" the urls load and stream fine on my chromecast device. However, when I run the castVideos app with my new registered Style Reciever Application app ID it gets the below error.  

When chromecast starts up it gets `Failed to load resource: the server responded with a status of 404`

in `Load message received` **the urls look fine** however in the sections `[cast.receiver.IpcChannel] IPC message sent:` **below the urls all have a "backslash" added to them** 

`
Failed to load resource: the server responded with a status of 404 ()
cast_receiver.js:67  [  0.264s] [cast.receiver.CastReceiverManager] Version: 2.0.0.0050
https://www.gstatic.com/eureka/player/undefined Failed to load resource: the server responded with a status of 404 ()
cast.receiver.logger.setLevelValue(cast.receiver.LoggerLevel.DEBUG);
undefined
cast_receiver.js:67  [ 23.548s] [cast.receiver.IpcChannel] Received message: {"data":"{\"repeatMode\":\"REPEAT_OFF\",\"currentTime\":0,\"requestId\":5,\"type\":\"QUEUE_LOAD\",\"items\":[{\"media\":{\"metadata\":{\"posterUrl\":\"https:\\/\\/img.solarcdn.ru\\/\\/2017\\/04\\/14\\/poster\\/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"images\":[{\"url\":\"https:\\/\\/img.solarcdn.ru\\/\\/2017\\/04\\/14\\/poster\\/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":480,\"height\":720},{\"url\":\"https:\\/\\/img.solarcdn.ru\\/\\/2017\\/04\\/14\\/poster\\/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":780,\"height\":1200}],\"title\":\"Trailer: Before I Fall\",\"description\":\"The film opens with the main character is Samantha Kingston, who has a perfect life. Then, everything changes. After one fateful night, she wakes up with no future at all. Then, she begins to question just how perfect her life really was. What awaits ahead?\",\"studio\":\"IMDb: 6.5\",\"metadataType\":1},\"tracks\":[{\"language\":\"en-US\",\"subtype\":\"CAPTIONS\",\"trackContentType\":\"text\\/vtt\",\"type\":\"TEXT\",\"trackId\":1,\"name\":\"English Subtitle\"}],\"contentId\":\"https:\\/\\/r9---sn-i3b7knel.googlevideo.com\\/videoplayback?requiressl=yes&initcwndbps=2465000&key=yt6&mime=video\\/mp4&source=youtube&upn=gOIVUtXgrbE&itag=22&sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&signature=B70993E557F80086D12AE18890620A33BF9C5031.4FDBB47664C776959C1557D06A605A2291B0B832&ip=219.73.46.7&ms=au&ei=a2T2WPLfFaaJ4gL1xrewDw&mv=m&pl=19&ipbits=0&id=o-ACkhP3pjIoL6TfranCG_dPoLq9wt_1hJ1y3XtP5x1mhC&mn=sn-i3b7knel&mt=1492542266&mm=31&dur=149.327&lmt=1479634536140535&expire=1492564171&ratebypass=yes\",\"contentType\":\"videos\\/mp4\",\"streamType\":\"BUFFERED\",\"duration\":149},\"preloadTime\":0,\"autoplay\":true}],\"startIndex\":0}","namespace":"urn:x-cast:com.google.cast.media","senderId":"a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF"}
cast_receiver.js:67  [ 23.555s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:67  [ 23.565s] [cast.receiver.MediaManager] MediaManager message received
cast_receiver.js:67  [ 23.567s] [cast.receiver.MediaManager] Dispatching MediaManager queueLoad event
cast_receiver.js:67  [ 23.576s] [cast.receiver.MediaManager] Dispatching MediaManager load event

**Seems ok, urls below look good why won't this stream the urls**

cast_receiver.js:67  [ 23.578s] [cast.receiver.MediaManager] Load message received:{"type":"LOAD","requestId":5,"mediaSessionId":0,"customData":null,"media":{"metadata":{"posterUrl":"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg","images":[{"url":"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg","width":480,"height":720},{"url":"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg","width":780,"height":1200}],"title":"Trailer: Before I Fall","description":"The film opens with the main character is Samantha Kingston, who has a perfect life. Then, everything changes. After one fateful night, she wakes up with no future at all. Then, she begins to question just how perfect her life really was. What awaits ahead?","studio":"IMDb: 6.5","metadataType":1},"tracks":[{"language":"en-US","subtype":"CAPTIONS","trackContentType":"text/vtt","type":"TEXT","trackId":1,"name":"English Subtitle"}],"contentId":"https://r9---sn-i3b7knel.googlevideo.com/videoplayback?requiressl=yes&initc…66&mm=31&dur=149.327&lmt=1479634536140535&expire=1492564171&ratebypass=yes","contentType":"videos/mp4","streamType":"BUFFERED","duration":149},"autoplay":true,"currentTime":0}

**Backslash added below in the IPC message sent, how do I see these sent error messages in iOS xcode**

cast_receiver.js:67  [ 23.604s] [cast.receiver.MediaManager] Sending broadcast status message
cast_receiver.js:67  [ 23.610s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.media","senderId":"*:*","data":"{\"type\":\"MEDIA_STATUS\",\"status\":[{\"mediaSessionId\":1,\"playbackRate\":1,\"playerState\":\"IDLE\",\"currentTime\":0,\"supportedMediaCommands\":15,\"volume\":{\"level\":1,\"muted\":false},\"media\":{\"metadata\":{\"posterUrl\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"images\":[{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":480,\"height\":720},{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":780,\"height\":1200}],\"title\":\"Trailer: Before I Fall\",\"description\":\"The film opens with the main character is Samantha Kingston, who has a perfect life. Then, everything changes. After one fateful night, she wakes up with no future at all. Then, she begins to question just how perfect her life really was. What awaits ahead?\",\"studio\":\"IMDb: 6.5\",\"metadataType\":1},\"tracks\":[{\"language\":\"en-US\",\"subtype\":\"CAPTIONS\",\"trackContentType\":\"text/vtt\",\"type\":\"TEXT\",\"trackId\":1,\"name\":\"English Subtitle\"}],\"contentId\":\"https://r9---sn-i3b7knel.googlevideo.com/videoplayback?requiressl=yes&initc…6&mm=31&dur=149.327&lmt=1479634536140535&expire=1492564171&ratebypass=yes\",\"contentType\":\"videos/mp4\",\"streamType\":\"BUFFERED\",\"duration\":149},\"currentItemId\":1,\"extendedStatus\":{\"playerState\":\"LOADING\",\"media\":{\"metadata\":{\"posterUrl\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"images\":[{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":480,\"height\":720},{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":780,\"height\":1200}],\"title\":\"Trailer: Before I Fall\",\"description\":\"The film opens with the main character is Samantha Kingston, who has a perfect life. Then, everything changes. After one fateful night, she wakes up with no future at all. Then, she begins to question just how perfect her life really was. What awaits ahead?\",\"studio\":\"IMDb: 6.5\",\"metadataType\":1},\"tracks\":[{\"language\":\"en-US\",\"subtype\":\"CAPTIONS\",\"trackContentType\":\"text/vtt\",\"type\":\"TEXT\",\"trackId\":1,\"name\":\"English Subtitle\"}],\"contentId\":\"https://r9---sn-i3b7knel.googlevideo.com/videoplayback?requiressl=yes&initc…6&mm=31&dur=149.327&lmt=1479634536140535&expire=1492564171&ratebypass=yes\",\"contentType\":\"videos/mp4\",\"streamType\":\"BUFFERED\",\"duration\":149}},\"repeatMode\":\"REPEAT_OFF\"}],\"requestId\":0}"}
cast_receiver.js:67  [ 24.875s] [cast.receiver.MediaManager] Sending error message to a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF
cast_receiver.js:67  [ 24.889s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.media","senderId":"a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF","data":"{\"requestId\":5,\"type\":\"LOAD_FAILED\"}"}
cast_receiver.js:67  [ 33.553s] [cast.receiver.IpcChannel] Received message: {"data":"{\"type\":\"GET_STATUS\",\"requestId\":6,\"mediaSessionId\":1}","namespace":"urn:x-cast:com.google.cast.media","senderId":"a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF"}
cast_receiver.js:67  [ 33.555s] [cast.receiver.CastMessageBus] Dispatching CastMessageBus message
cast_receiver.js:67  [ 33.558s] [cast.receiver.MediaManager] MediaManager message received
cast_receiver.js:67  [ 33.561s] [cast.receiver.MediaManager] Dispatching MediaManager getStatus event
cast_receiver.js:67  [ 33.564s] [cast.receiver.MediaManager] onGetStatus
cast_receiver.js:67  [ 33.567s] [cast.receiver.MediaManager] onGetStatus: {"requestId":6,"mediaSessionId":1}
cast_receiver.js:67  [ 33.571s] [cast.receiver.MediaManager] Sending status message to a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF
cast_receiver.js:67  [ 33.577s] [cast.receiver.IpcChannel] IPC message sent: {"namespace":"urn:x-cast:com.google.cast.media","senderId":"a8d32aff-2648-bed0-32cd-48f4bc7e510f.25:ACC878B8-2A52-4221-99CD-EDE81BD73ABF","data":"{\"type\":\"MEDIA_STATUS\",\"status\":[{\"mediaSessionId\":1,\"playbackRate\":1,\"playerState\":\"IDLE\",\"currentTime\":0,\"supportedMediaCommands\":15,\"volume\":{\"level\":1,\"muted\":false},\"media\":{\"metadata\":{\"posterUrl\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"images\":[{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":480,\"height\":720},{\"url\":\"https://img.solarcdn.ru//2017/04/14/poster/5802ca094d8fa31175332f9bc02c6dca-before-i-fall.jpg\",\"width\":780,\"height\":1200}],\"title\":\"Trailer: Before I Fall\",\"description\":\"The film opens with the main character is Samantha Kingston, who has a perfect life. Then, everything changes. After one fateful night, she wakes up with no future at all. Then, she begins to question just how perfect her life really was. What awaits ahead?\",\"studio\":\"IMDb: 6.5\",\"metadataType\":1},\"tracks\":[{\"language\":\"en-US\",\"subtype\":\"CAPTIONS\",\"trackContentType\":\"text/vtt\",\"type\":\"TEXT\",\"trackId\":1,\"name\":\"English Subtitle\"}],\"contentId\":\"https://r9---sn-i3b7knel.googlevideo.com/videoplayback?requiressl=yes&initc…6&mm=31&dur=149.327&lmt=1479634536140535&expire=1492564171&ratebypass=yes\",\"contentType\":\"videos/mp4\",\"streamType\":\"BUFFERED\",\"duration\":149},\"currentItemId\":1,\"idleReason\":\"ERROR\"}],\"requestId\":6}"}
`

**Comment by entertailion** [comment]
This is not about the reference receiver. File Cast SDK bugs here: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by shashu10** [comment]
@alexrmacleod is this still an issue?

**Comment by alexrmacleod** [comment]
Hi
nope thanks for asking

Best,
A.
m: +852 91300844
w: www.goeasysmile.com <http://www.goeasysmile.com/> | nextmelody.com <http://nextmelody.com/> | tipp3d.com <http://tipp3d.com/> | angel.co/alex-macleod-1 <https://angel.co/alex-macleod-1>
