### ISSUE TITLE
Support for Time Shift in HLS on ChromeCast

### ISSUE THREAD

**Issue by ram992** [googlecast/CastReferencePlayer#36]
Hello,

Sorry for raising this as an issue, but can I get information on implementing the live seek Back on chromecast.
Currently I am  passing the necessary "dw" param in the url and it is working with ExoPlayer, 
but chromecast is playing the delayed feed and not seeking forward (without the param it is working fine).

And also can you specify any param that I need to use to get a callback from the chromecast that seeking back is supported in live, So that I can show the seekbar.

**Comment by entertailion** [comment]
We do support both seeking forwards and backwards for HLS live streaming. You can send SeekRequestData (https://developers.google.com/cast/docs/reference/receiver/cast.receiver.MediaManager.SeekRequestData) with the currentTime or the relativeTime to seek.
player.getState() (https://developers.google.com/cast/docs/reference/player/cast.player.api.Player#getState) is also accessible to get a seekable range. To get a callback, you can listen to the SEEK event.

**Comment by oleynikd** [comment]
@entertailion Could you please help me setting up player for playing back Live HLS? I tried both default and custom cast players based on this reference. In my Live HLS stream there is a 10 minutes "live window". Playback always starts from the oldest available chunk (10 min ago). How do I start playback from "live" position (newest chunk)?

Thanks.

**Comment by entertailion** [comment]
Please file an issue on our tracker: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
