### ISSUE TITLE
Problem with seek bar while streaming live video

### ISSUE THREAD

**Issue by bansalvks** [googlecast/CastReferencePlayer#41]
Hello Team,

It is wonderful library and I am using it from quite long time and never faced any issue but now I am in a very hard situation.

The problem is that while chrome-casting/steaming live video, current time is changing but seek bar is showing pointer in (left most) beginning as it should be in the right most so that user can go backward, also the final time is `00:00` where it should be the time as much as it has been played. 

If video is getting played on android device directly then the seek bar is working fine. But in casting the seek bar is not growing.

**Casting**
![screenshot_20170724-125840](https://user-images.githubusercontent.com/8565993/28512875-5377ed54-7071-11e7-9b9e-a12350f9ca0e.png)

**Playing on android**
![screenshot_20170724-130108](https://user-images.githubusercontent.com/8565993/28512881-5ca9503e-7071-11e7-8e75-9c08268e1db8.png)

**Comment by entertailion** [comment]
This is not a bug with the receiver. Please update to the latest version of the Cast Android SDK.
