### ISSUE TITLE
custom User-Agent?

### ISSUE THREAD

**Issue by jboisjo** [googlecast/CastReferencePlayer#42]
Hi,

is is possible to change or update the user-agent on the Cast Receiver app?

I've tried to add it on the manifest, but no success.

```
 host.updateManifestRequestInfo = function(requestInfo) {
      requestInfo.withCredentials = true;
      requestInfo.headers = {};
      requestInfo.headers['User-Agent'] = 'mycustomuseragent';
      };
```

Is there any other way? 

Thank you so much!

**Comment by entertailion** [comment]
The user-agent is set by the browser, which in this case is the Chrome browser that the cast receiver device uses.
