### ISSUE TITLE
HLS Livestream not playing

### ISSUE THREAD

**Issue by JuliusThms** [googlecast/CastReferencePlayer#43]
Hello, 

i don't if this is the right place, but can you explain why the second hls URL is not playing. 
The receiver does not throw any error.

Works: http://daserste_live-lh.akamaihd.net/i/daserste_de@91204/master.m3u8
Works not: https://sdn-global-live-http-cache.3qsdn.com/live/_definst_/smil:6003-mbr.smil/playlist.m3u8

Also tried to use option: preferSequenceNumberForPlaylistMatching

**Comment by entertailion** [comment]
File any playback issues against the SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
