### ISSUE TITLE
Player stuck on an IDLE state and doesn't respond

### ISSUE THREAD

**Issue by aleksandrc-hyuna** [googlecast/CastReferencePlayer#44]
I am trying to fix the issue when a sender (android app) send a queue of audio items. Few of those items can be with an invalid URL
When it happens the receiver occurs an error and set the player to an IDLE state.
Then I try to click on play next button or do something else on my android app - the receiver doesn't respond.

![image](https://user-images.githubusercontent.com/17985346/31494474-170ddc96-af5c-11e7-96f2-95b240707d54.png)
![image](https://user-images.githubusercontent.com/17985346/31494514-4488b9ac-af5c-11e7-9561-b479558fab6f.png)

**Comment by entertailion** [comment]
It is up to your app logic to not send invalid URL's. Also, this receiver is not recommended for new development. We recommend you migrate to the Cast Application Framework (CAF) Receiver. Also see the Basic CAF Receiver sample app: https://github.com/googlecast/BasicReceiverCAF

**Comment by aleksandrc-hyuna** [comment]
But if it happens (for examples the URL expires when receiver get it) what I need to do?

**Comment by entertailion** [comment]
It is unlikely that support for your invalid URL will be added to the SDK since all development are now only done on the CAF receiver SDK.

**Comment by PablitoUA** [comment]
I have exacly the same issue.
URL is valid but for reasons beyond of my control streaming server responce with an error e.g. "track not found".
After that remote player goes into a coma and don't start playing even if I reload whole queue.

**Comment by entertailion** [comment]
You can file a bug against the Cast receiver SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by aleksandrc-hyuna** [comment]
Thanks, I've already done it and waiting for response
