### ISSUE TITLE
This error is not sent back to the sender app: Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': 

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastReferencePlayer#6]
I have an m3u8 file that apparently is not supported by the Chromecast however my sender app is never notified that the file failed to play. 

The error: 

Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp2t; codecs="avc1.66.31,mp4a.40.2"') is unsupported.media_player.js:102 memedia_player.js:111 Demedia_player.js:118 h.updatemedia_player.js:117 h.openmedia_player.js:219 h.Hf

The m3u8 looks like this:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2048805,CODECS="avc1.66.31,mp4a.40.2",RESOLUTION=1280x720
chunklist_w517510829.m3u8

**Comment by entertailion** [comment]
Please provide a complete log and sample stream to reproduce the issue.

**Comment by mntgoat** [comment]
It doesn't even need the video file, gives the error right away after loading the m3u8, never touches the other m3u8 listed in there or the ts file. 

You can try it here http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8

Here are the logs:

 [ 19.728s] [cast.player.api.Player] unload 
media_player.js:20  [ 19.781s] [cast.player.api.Player] Version: 1.0.0.13
media_player.js:20  [ 19.798s] [cast.player.api.Player] load 
webvideo.html:1 Mixed Content: The page at 'MyChromecastWebappURL' was loaded over HTTPS, but requested an insecure image 'http://192.168.1.209:30001/thumbnail/1776/http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8'. This content should also be served over HTTPS.
media_player.js:20  [ 19.847s] [cast.player.core.MediaSourceManager] open
webvideo.html:1 Mixed Content: The page at 'MyChromecastWebappURL' was loaded over HTTPS, but requested an insecure image 'http://192.168.1.209:30001/thumbnail/1776/http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8'. This content should also be served over HTTPS.
media_player.js:20  [ 19.890s] [cast.player.core.MediaSourceManager] sourceopen
media_player.js:20  [ 19.920s] [goog.net.XhrIo] Opening Xhr [GET http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8 -1]
media_player.js:20  [ 19.941s] [goog.net.XhrIo] Will abort after 30000ms if incomplete, xhr2 false [GET http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8 -1]
media_player.js:20  [ 19.959s] [goog.net.XhrIo] Sending request [GET http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8 -1]
media_player.js:34 Mixed Content: The page at 'MyChromecastWebappURL' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8'. This content should also be served over HTTPS.
media_player.js:20  [ 20.221s] [goog.net.XhrIo] Request complete [GET http://d5c96afa2397609c09da-31b7649d53236d244fbf8883e15126c9.r89.cf5.rackcdn.com/test/video.m3u8 200]
media_player.js:80 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp2t; codecs="avc1.66.31,mp4a.40.2"') is unsupported.

**Comment by entertailion** [comment]
Is this still an issue?

**Comment by mntgoat** [comment]
Nope, doesn't seem to be an issue anymore.
