### ISSUE TITLE
Is there a chance you will add support for still pictures?

### ISSUE THREAD

**Issue by fabricapo** [googlecast/CastReferencePlayer#7]
The receiver can handle videos and audios, but not pictures (e.g. JPG), which the Styled Receiver can handle (I get [cast.receiver.MediaManager] Load metadata error: when I try). Is there a chance you will add support for pictures in the future?

Thanks,

   fabrizio

**Comment by entertailion** [comment]
Not planned to support images. Especially since their is now Cast UX for image apps.
