### ISSUE TITLE
Chromecast 1 Issues

### ISSUE THREAD

**Issue by objectiveCarlo** [googlecast/CastReferencePlayer#9]
Hi 

I am trying to play live smoothstreaming with playready in chromecast 1 with your castreference player
But it is just pausing then playing then pausing.

Also some of our none live smoothstreaming with playready videos is not displaying correctly. The videos are just bunch of colors in the screen.

Though in chromecast 2 this issues are not happening.

What to do?

The log of the live stream is in here: https://gist.github.com/objectiveCarlo/f573d2b67f300eb0d733

**Comment by entertailion** [comment]
Please fill in this form and provide us with a sample stream and license so we can reproduce your issue: https://support.google.com/cast-developer/contact/google_cast_contact_us?hl=en&rd=1

**Comment by objectiveCarlo** [comment]
done
